# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e01c0154ecab805c30a424ed8d36956e5f2cbba5d245e42687546bdccad530877f130c73e4d1373eb5358dd57affed371556d518729aa58595e664345f007669

test:
  secret_key_base: 77ce7d3d32be963c147d9c027115bf1d0a947fc22930df925635a77a74efdde6b6fa24b4944d7cd2e81091213b4dd151e1108d49559be4db3fed7cb3da18510a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
